/**************************************
    Webutler V2.1 - www.webutler.de
    Copyright (c) 2008 - 2011
    Autor: Sven Zinke
    Free for any use
    Lizenz: GPL
**************************************/

(function(){var a=null,b=CKEDITOR.tools.cssLength;function c(e,f){var g='',h=e.split(';');for(var i=0;i<h.length;i++){var j=h[i].split(':');if(CKEDITOR.tools.trim(j[0]).toLowerCase()==f){g=CKEDITOR.tools.trim(j[1]);break;}}return g?g:'';};function d(e,f,g,h){var i=e.createFakeParserElement(f,'cke_gmap','googlemap',true),j=i.attributes.style||'';j=i.attributes.style=j+'width:'+b(g)+';';j=i.attributes.style=j+'height:'+b(h)+';';return i;};CKEDITOR.plugins.add('gmap',{lang:[CKEDITOR.lang.detect(CKEDITOR.config.language)],init:function(e){CKEDITOR.document.appendStyleSheet(this.path+'dialogs/mapinfowin.css');e.addCss('img.cke_gmap {\tbackground-image: url('+CKEDITOR.getUrl(this.path+'mapfakeimg.gif')+');'+'\tbackground-position: center center;'+'\tbackground-repeat: no-repeat;'+'\tborder: 1px solid #A9A9A9;'+'}');e.addCommand('gmap',new CKEDITOR.dialogCommand('gmap'));e.ui.addButton('gMap',{label:e.lang.googlemaps.title,icon:this.path+'gmap.png',command:'gmap'});e.on('doubleclick',function(f){var g=f.data.element;if(g.is('img')&&g.data('cke-real-element-type')=='googlemap')f.data.dialog='gmap';else return null;});if(e.addMenuItems)e.addMenuItems({googlemaps:{label:e.lang.googlemaps.title,icon:this.path+'gmap.png',command:'gmap',group:'googlemaps'}});if(e.contextMenu)e.contextMenu.addListener(function(f,g){if(f&&f.is('img')&&!f.isReadOnly()&&f.data('cke-real-element-type')=='googlemap')return{googlemaps:CKEDITOR.TRISTATE_OFF};else return null;});CKEDITOR.dialog.add('gmap',this.path+'dialogs/gmap.js');},afterInit:function(e){var f=e.dataProcessor,g=f&&f.dataFilter;if(g)g.addRules({elements:{div:function(h){var i=h.attributes;if(i['class']=='googlemapsframe'){var j=c(i.style,'width')||'100',k=c(i.style,'height')||'100';return d(e,h,j,k);}}}});},requires:['dialog','iframedialog','fakeobjects']});})();
