<?php defined('BASEPATH') OR exit('No direct script access allowed');
$route['blog/rss/all.rss']='blog/rss/index';
$route['blog']	= 'blog';
$route['blog/positive/(:num)?']	= 'blog/category/positive/$2';
$route['blog/positive/(:any)?']	= 'blog/view/$1';
$route['blog/positive']= 'blog/category/positive';
$route['blog/beautiful/(:num)?']	= 'blog/category/beautiful/$2';
$route['blog/beautiful/(:any)?']	= 'blog/view/$1';
$route['blog/beautiful']= 'blog/category/beautiful';
$route['blog/animals/(:num)?']	= 'blog/category/animals/$2';
$route['blog/animals/(:any)?']	= 'blog/view/$1';
$route['blog/animals']= 'blog/category/animals';
$route['blog/environment/(:num)?']	= 'blog/category/environment/$2';
$route['blog/environment/(:any)?']	= 'blog/view/$1';
$route['blog/environment']= 'blog/category/environment';
$route['blog/food/(:num)?']	= 'blog/category/food/$2';
$route['blog/food/(:any)?']	= 'blog/view/$1';
$route['blog/food']= 'blog/category/food';
$route['blog/search']					= 'blog/search';
$route['blog/tagged/(:any)?']			= 'blog/tagged/$1';
$route['blog/rss/all.rss']			= 'blog/rss/index';
$route['blog/(:num)?']				= 'blog/index/$1';
$route['blog/rss/(:any).rss']		    = 'blog/rss/category/$1';
$route['blog/admin/categories(/:any)?']		= 'admin_categories$1';
/* End of file routes.php */